### ISSUE TITLE
Add mention of DNS_PING 

### ISSUE THREAD

**Issue by thomasdarimont** [zhangliqiang/keycloak-cluster-setup-and-configuration#3]
DNS_PING is often used in Kubernetes keycloak setup and works quite well in practice.

It's also used by the keycloak Helm chart
https://github.com/helm/charts/blob/master/stable/keycloak/templates/statefulset.yaml#L92

**Comment by zhangliqiang** [comment]
Hi Thomas,
Sorry for the missing, DNS_PING has just been added.
